name: prebuilds
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Build prebuilds
        uses: ./.github/actions/build
        env:
          JOBS: 3
      - name: Upload prebuilds
        uses: actions/upload-artifact@v1
        with:
          name: prebuilds
          path: prebuilds

  build-other:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install --ignore-scripts
      - run: npm run build-prebuild
        env:
          JOBS: 3
      - run: npm run build-prebuild -- -a arm64
        if: runner.os == 'macOS'
        env:
          JOBS: 3
      - name: Upload prebuilds
        uses: actions/upload-artifact@v1
        with:
          name: prebuilds
          path: prebuilds
